from django.db import models

'''
The User Model has fields username,email and password and id field generated by default
'''
class User(models.Model) :
    username = models.CharField(max_length=225)
    email = models.EmailField(max_length=225)
    password = models.CharField(max_length=225)

'''
The Project Model has fields userID which has PK-FK relationship with User model,name,description and created on timestamp
'''
class Project(models.Model) :
    userID = models.IntegerField()
    name = models.CharField(max_length=225)
    description = models.CharField(max_length=225)
    createdOn = models.DateTimeField()
