# Generated by Django 3.0.2 on 2020-02-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20200209_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('createdOn', models.DateTimeField()),
            ],
        ),
    ]
